### PR TITLE
serviceworker webpacker generator integration fixes/enhancements

### PR DESCRIPTION
**Pull request by ncs1**
Hi, 
See issue #84
- fixes rubocop.yml
- fix the install generator to take care/modify accordingly when the project uses webpacker as its asset pipeline.
- updates README.
- uses @phstc and @stevenharman PR not merged.

### CODE REVIEW

**Comment by ncs1** [comment]
I would appreciate your comments regarding this. 
Currently I'm using my fork to work with the serviceworker under Webpacker env and it works great.
I tried to run the test suite but it seems broken, could you clarify ?
Thanks.

**Comment by aseroff** [comment]
seconded, would love some eyes on this

**Comment by rossta** [comment]
@ncs1 Thanks for working on these changes. The main branch is now passing on CircleCI. Would you like to rebase and fix the failing tests on your branch?

**Comment by ncs1** [comment]
@rossta good to see you here. 
This pull request is fairly intrusive; however, I'm using it without problems on my rails 6 app since its introduction here.
I'm fairly busy now, but I'll try to make time to rebase it and clean it up in the upcoming days - (feel free to take it/edit it/DIY as you see fit if you have time now).
In case that the rails app has both sprockets & webpacker, it'll generate the webpacker scaffold - should it be configurable on generate ?

**Comment by rossta** [comment]
Perhaps separate tasks would be the most straightforward?

```rails
$ rails g serviceworker:install::sprockets 
$ rails g serviceworker:install::webpacker
```

**Comment by ncs1** [comment]
Sorry for the delay, I didn't have much time - but I'm working on it.
Just so you know, running bin/setup and bin/rake for test is broken (as documented in the Development section in the readme). 
I managed to run the tests successfully through appraisal - but it wasn't evident and it'll need to be fixed or at least being documented in the readme... (I'll try to put it also)

**Comment by ncs1** [comment]
@rossta please review.
Updated readme.
Added dockerfile, that I used for the tests.
Added tests for the webpacker integration, it made the test suite slower due to the "rails webpacker:install" command on dir generation (making it 3 times in Appraisal test...).
(I'll try to optimize the test suite time when I'll have time, I can get rid of the webpacker:install on generation...)

**Comment by ncs1** [comment]
Now the test suite runs as before

**Comment by Paradoxor** [comment]
+1 for this will help a lot of rails 6 users

**Comment by Petrucheqa** [comment]
Hello, I'm new to rails and I would like to implement a service worker in my Rails app.

Its a rails 6 app and i'm a stuck because the gem seems to use sprockets instead of wekpacker.

By default my javascripts files are in` app/javascript` but the command generate files in `assets/javascripts` and I don't understand the configuration I should change to use files in `app/javascript`.

Can you tell me if it's possible at the moment ? Or I need to wait the merge of this branch onto master ? 

Thanks !

**Comment by ncs1** [comment]
Hi @Petrucheqa , 
You can use my repository where this branch is integrated to use it with Rails 6 on webpacker. 
https://github.com/ncs1/serviceworker-rails
Use the following in your Gemfile:
"""
gem(
  'serviceworker-rails',
  git: 'https://github.com/ncs1/serviceworker-rails.git',
  branch: 'master'
)
"""

And follow my instructions in the README there to integrate with webpacker.
All the best.

**Comment by Petrucheqa** [comment]
I'll try as soon as I can, thanks for your answer @ncs1 !

**Comment by juan-apa** [comment]
For those that want to use this version in their project, add this as the branch to be use by the gem by doing:
```
gem 'serviceworker-rails', git: 'https://github.com/ncs1/serviceworker-rails.git', branch: 'serviceworker_webpacker_enh'
```
this pulls the source code from this pr by @ncs1

**Pull request closed without merging**
