### PR TITLE
Update to Service Worker Companion  Message Name and Error Reporting

### PR DESCRIPTION
**Pull request by tonydehnke**
Edited console reporting to show Rails Service worker for clarity.

Added Error message to display error message.

I found this code in a different tutorial and it worked well, so though we should add it here.

### CODE REVIEW

**Comment by rossta** [comment]
@tonydehnke Thanks for the PR. Could you rebase from master to get a passing build?

**Comment by tonydehnke** [comment]
I will try, that might be above my experience level,  I'll do some reading on it as I've never done a rebase before (or something in a Gem for that matter).
If there is anything I should know or tips, I'm happy to hear them.

**Comment by rossta** [comment]
To rebase master on your fork, you would need to run some instructions locally to [sync with this repository](https://help.github.com/en/articles/syncing-a-fork).

I tried your changes locally but the tests failed due the copy change so you will need to edit the tests to get them to pass.

**Comment by tonydehnke** [comment]
Closed as I had to create a new branch after doing the sync with the master repository.  I created a new branch and have submitted a pull request with the test passing now.

**Pull request closed without merging**
